"""
1. Investigar como ocultar los mensajes, cuando no ingresa los valores tanto el DNI y la contraseña
2. tambien a la hora de maximizar la ventana que centre los componentes
3. Insertar el logo de la empresa
"""


from PyQt6 import QtCore, QtGui, QtWidgets

class VistaLogin(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 508)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_usuario = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_usuario.setGeometry(QtCore.QRect(70, 110, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        self.lbl_usuario.setFont(font)
        self.lbl_usuario.setObjectName("lbl_usuario")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 150, 281, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lbl_contrasenia = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_contrasenia.setGeometry(QtCore.QRect(70, 220, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        self.lbl_contrasenia.setFont(font)
        self.lbl_contrasenia.setObjectName("lbl_contrasenia")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 260, 281, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.btn_ingresar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_ingresar.setGeometry(QtCore.QRect(70, 370, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btn_ingresar.setFont(font)
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.lbl_olvido_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_olvido_password.setGeometry(QtCore.QRect(140, 330, 151, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        self.lbl_olvido_password.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        self.lbl_olvido_password.setFont(font)
        self.lbl_olvido_password.setIndent(0)
        self.lbl_olvido_password.setObjectName("lbl_olvido_password")
        self.lbl_campo_obligatorio = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_campo_obligatorio.setGeometry(QtCore.QRect(150, 430, 141, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        self.lbl_campo_obligatorio.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lbl_campo_obligatorio.setFont(font)
        self.lbl_campo_obligatorio.setIndent(0)
        self.lbl_campo_obligatorio.setObjectName("lbl_campo_obligatorio")
        self.btn_cancelar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_cancelar.setGeometry(QtCore.QRect(240, 370, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.lbl_ingrese_contrasenia = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_ingrese_contrasenia.setGeometry(QtCore.QRect(80, 300, 241, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        self.lbl_ingrese_contrasenia.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lbl_ingrese_contrasenia.setFont(font)
        self.lbl_ingrese_contrasenia.setIndent(0)
        self.lbl_ingrese_contrasenia.setObjectName("lbl_ingrese_contrasenia")
        self.lbl_ingrese_usuario = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_ingrese_usuario.setGeometry(QtCore.QRect(70, 190, 241, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        self.lbl_ingrese_usuario.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lbl_ingrese_usuario.setFont(font)
        self.lbl_ingrese_usuario.setIndent(0)
        self.lbl_ingrese_usuario.setObjectName("lbl_ingrese_usuario")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Inicio de Sesión"))
        self.lbl_usuario.setText(_translate("MainWindow", "* Usuario"))
        self.lbl_contrasenia.setText(_translate("MainWindow", "* Contraseña"))
        self.btn_ingresar.setText(_translate("MainWindow", "Ingresar"))
        self.lbl_olvido_password.setText(_translate("MainWindow", "¿Olvidaste la contraseña?"))
        self.lbl_campo_obligatorio.setText(_translate("MainWindow", "* Campos obligatorios"))
        self.btn_cancelar.setText(_translate("MainWindow", "Cancelar"))
        ##Ver como ocultar estos mensajes!!!!
        self.lbl_ingrese_contrasenia.setText(_translate("MainWindow", "Ingrese su contraseña... por favor.")) 
        self.lbl_ingrese_usuario.setText(_translate("MainWindow", "Ingrese su DNI... por favor."))

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = VistaLogin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
"""